# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

# Run tests on Ubuntu and macOS
os:
  - linux
  - osx
# Ubuntu 14.04
dist: trusty

# Generic language as travis doesn't know anything about SPM and Linux
language: generic
sudo: required

osx_image: xcode9.2
xcode_sdk: iphonesimulator11.2
# cache: cocoapods
# podfile: Example/Podfile
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod repo update
  - pod install --project-directory=Example
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      brew install kylef/formulae/swiftenv;
      if which swiftenv > /dev/null; then eval "$(swiftenv init -)"; fi;
    else
      git clone https://github.com/kylef/swiftenv.git ~/.swiftenv;
      export SWIFTENV_ROOT="$HOME/.swiftenv";
      export PATH="$SWIFTENV_ROOT/bin:$PATH";
      eval "$(swiftenv init -)";
    fi
  - swiftenv install $(cat .swift-version) # Install swift with swiftenv
  - swiftenv global $(cat .swift-version)
script:
  # Output something every 10 minutes or Travis kills the job
  - while sleep 60; do echo "=====[ $SECONDS seconds still running ]====="; done &
  # Actual script
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/Web3.xcworkspace -scheme Web3-Example -sdk iphonesimulator11.2 -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.2' ONLY_ACTIVE_ARCH=NO | xcpretty;
      pod lib lint --allow-warnings;
    fi
  - swift build
  - swift build -c release
  - swift test
  # Kill background echo job
  - kill %1
after_success:
  - if [ $TRAVIS_OS_NAME == "osx" ]; then bash <(curl -s https://codecov.io/bash); fi
